
version: 2.1
jobs:
  say-hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "make file"
          command: "echo Hello semoo from work space >/home/circleci/out.txt"
      - run:
          name: "PWD"
          command: "pwd"
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - out.txt

  get_file_from_work_space:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci
      - run:
          name: "get_file_from_work_space"
          command: "cat /home/circleci/out.txt"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - get_file_from_work_space