
version: 2.1
jobs:
  say-hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout   
      - run:
          name: "PWD"
          command: "pwd"
      - run:
          name: "cd"
          command: "cd"
      - run:
          name: "PWD sec"
          command: "pwd"
      - run:
          name: "make file"
          command: "echo Hello semoo from work space >~/out.txt"
      - run:
          name: "PWD"
          command: "pwd"
      - persist_to_workspace:
          root: ~/
          paths:
            - out.txt

  get_file_from_work_space:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: "get_file_from_work_space"
          command: "cat ~/out.txt"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - get_file_from_work_space