version: 2.1

commands:
  sayhello:
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}
jobs:
  job1:
    docker:
      - image : circleci/node:13.8.0   
    steps:
      run : sayhello
workflows:
  deploy-step-workflow:
    jobs:
      - job1
