
version: 2.1
jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello semoo from work space > ~/out.txt"
      - persist_to_workspace:
          root: ~/
          paths:
            - out.txt
      - attach_workspace:
          at: ~/
      - run:
          name: "get_file_from_work_space"
          command: "cat ~/out.txt"
      

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
     